### ISSUE TITLE
Drilldown Issues

### ISSUE THREAD

**Issue by ccl0utier** [alatif113/mitre_attck_heatmap#11]
Hi Mohammed,

Currently, it seems like the provided drilldowns for `$row.mtr_technique$` and `$row.mtr_tactic$` have the following shortcomings:

- There is no token for the sub techniques and it's not provided in `$row.mtr_technique$`
- Clicking on a technique when it's empty doesn't update `$row.mtr_technique$`

For reference:

![image](https://user-images.githubusercontent.com/58239192/236870326-14077965-83a4-445d-87fc-00a179c713ef.png)

Can that be added please?

**Comment by alatif113** [comment]
Hi, 

Thanks for the find. I am working on a fix and should have a new release shortly.

**Comment by alatif113** [comment]
Fixed in v1.7.2. Will take some time to get reapproved through Splunkbase, but feel free to download the latest from Github.

**Comment by ccl0utier** [comment]
Awesome, thanks Mohammed.  You rock!
