### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by jkraycer1** [alatif113/mitre_attck_heatmap#15]
When running the file, I get key error at line 54. It seems that the json file is not working properly...

```
Traceback (most recent call last):
  File "/root/mitremapping/mitre/mitre_attck_heatmap-1.8.1/bin/enterpriseAttack2json.py", line 54, in <module>
    'platform': obj['x_mitre_platforms']
KeyError: 'x_mitre_platforms'
```

**Comment by alatif113** [comment]
The JSON format changed in recent versions of ATT&CK and D3FEND. Updated the parser for the newer formats.
