### ISSUE TITLE
Disappearing visualization

### ISSUE THREAD

**Issue by Aezingg** [alatif113/mitre_attck_heatmap#16]
Hello guys,

I'm just discovering this application and I'm delighted with what it can do.

However, the first 5 seconds are perfect, but after that time, the colors on the techniques start to disappear without me touching anything...

Is this normal? 

![chrome_25_07_24_09_34](https://github.com/user-attachments/assets/657a26fe-593b-4d3f-b1b5-7d8bd5139c69)
![chrome_25_07_24_09_37](https://github.com/user-attachments/assets/4c6b7287-1e8f-4553-a53b-a37f75a126cb)

Here's the search I use 

```
`notable`
| rename annotations.mitre_attack.mitre_technique_id AS id
| stats count AS "Detection Count" by id
| table id "Detection Count"
```

Thank you for your help

**Comment by alatif113** [comment]
You most likely have animations turned on. When on, the visualization flips through all the colors sequentially.  Please disable it in the panels configuration settings, when you go to edit mode of your dashboard. Let me know if this works.

**Comment by Aezingg** [comment]
You're right, after deactivating the animations I can now see the colors normally. Thank you very much for the solution !
