### ISSUE TITLE
Uncomplete visualization when using display layout "Name"

### ISSUE THREAD

**Issue by Daavide** [alatif113/mitre_attck_heatmap#3]
Basically just the "Defense Evasion" list, when using display layout "Name", is not completely displayed. Even changing panel dimension in XML, it does not work.
In this case also the Legend is not displayed

![image](https://user-images.githubusercontent.com/15834861/152383736-8f917e21-10a5-4cab-988d-acc265cfa4e9.png)

![image](https://user-images.githubusercontent.com/15834861/152383838-344dd7f7-f285-454f-888e-deb193e296d9.png)

**Comment by alatif113** [comment]
Thanks for bringing this to my attention. Looks like this is due to a limitation in Splunk where the panel has a max height set. Will look into this and see if there is a way around this limit.

**Comment by alatif113** [comment]
A work around to increase the panel height is to manually override the dashboards style sheet. You can do this in one of two ways:

**Option 1**

1. Add an ID to your panel, by editing the XML directly 
`<panel id="myPanelId">`
2. Add a custom stylesheet to your dashboard, located within `%SPLUNK_HOME%/etc/apps/<your_app>/appserver/static/`
`<dashboard stylesheet="myCustomStyleSheet.css">`
3. Set the contents of your custom style sheet to (where myPanelId matches the ID set in step 1):
`#myPanelId .ui-resizable {
          height: 1400px !important;
        }`
4. Adjust the height in pixels as needed

**Option 2**

1. Add an ID to your panel, by editing the XML directly 
`<panel id="myPanelId">`
2. Edit the XML view and add a new row with the following contents (where myPanelId matches the ID set in step 1):
```
<row depends="$hidden$">
     <html>
         <style>
             #myPanelId .ui-resizable {
                 height: 1400px !important;
             }
          </style>
     </html>
</row>
```
4. Adjust the height in pixels as needed

**Comment by Daavide** [comment]
Thanks!!
