### ISSUE TITLE
MITRE ATT&CK Version Update

### ISSUE THREAD

**Issue by cjohnston33** [alatif113/mitre_attck_heatmap#4]
Hello! I was wanting to know if you had plans on releasing a version update to support MITRE version 11?

**Comment by sangeethsuseelan** [comment]
Did you get an updated version?

**Comment by alatif113** [comment]
Hi, due to my current work schedule, unfortunately not anytime soon. The plan, however, is to eventually allow a dropdown to choose the MITRE version.

**Comment by sangeethsuseelan** [comment]
That would be great.

I have seen a js (visualization.js) file which has the Tactic and Technic details of the MITRE. Thinking of updating the same latest MITRE version (v11). For the time being, will that help?

**Comment by alatif113** [comment]
Yes, if you want to directly update /appserver/static/visualizations/mitre_attck_heatmap/visualization.js you can. Unfortunately the code is built using nodejs, so it may not be formatted to be user friendly.

**Comment by alatif113** [comment]
Version updated to enterprise attack v12, GitHub has the latest package and currently being processed by Splunkbase.
