### ISSUE TITLE
App is not compatible with Search Head Cluster

### ISSUE THREAD

**Issue by s-m-p** [alatif113/mitre_attck_heatmap#5]
App cannot be installed on our Cloud stack because it is not compatible with a Search Head Cluster:

![image](https://user-images.githubusercontent.com/38626196/197620761-e7a54827-f279-472f-a9e2-91b5e0b9dcda.png)

**Comment by alatif113** [comment]
Submitted updated version which should support search head clusters. Going through the Splunkbase appinspect approval process now.

**Comment by s-m-p** [comment]
I appears the app is available for me to install now through the Browse Apps interface. Thank you for resolving this!
