### ISSUE TITLE
Failed to load source for MITRE ATT&CK Heatmap Visualization

### ISSUE THREAD

**Issue by Cyberguy4lyfe** [alatif113/mitre_attck_heatmap#6]
Thank you so much for updating this. I struggled while trying to convert the v9 to v12. This app is so great for me because it allows me to create a custom dashboard with custom drilldowns using the visualization. Unfortunately, I am getting the Failed to Load Source error for the visualization and I can't find the problem. I am using ES 9.0.1 on a single Splunk instance hosted on a windows 11 machine. The MITRE ATT&CK Framework App is updated to version 3.7.0 and the Heatmap app is version 1.5.0. I did not have this issue before, so I was hoping you had some insight that might help me troubleshoot the issue.

**Comment by alatif113** [comment]
Hi. Can you try clearing cache
