### ISSUE TITLE
Display sub-techniques

### ISSUE THREAD

**Issue by TheLawsOfChaos** [alatif113/mitre_attck_heatmap#7]
Could we have a way to display the sub-techniques? I know they are added up and counted in the current totals, but with mouse over it would be helped. I think that would be easier to implement that way then adding it live like Navigator does.

**Comment by alatif113** [comment]
Hi, good suggestion although easier said than done. Will think about this one for the next release, but no definitive timeline.

**Comment by alatif113** [comment]
This feature has been added in the latest release (1.6.1)
