### ISSUE TITLE
Add the ability to switch between different matrices

### ISSUE THREAD

**Issue by ccl0utier** [alatif113/mitre_attck_heatmap#8]
It would be great if we could filter the visualization between the different MITRE ATT&CK [matrices and sub-categories](https://attack.mitre.org/matrices/enterprise/).  

For example, show `ICS`, `Windows` or `Office 365` only, etc.

Happy to pitch in if that helps!

**Comment by alatif113** [comment]
Hi. Cool idea. Will look into this.

**Comment by alatif113** [comment]
Check out the updates on the master branch. Got the feature working. May need to clear cache. Going to do some additional testing before pushing a new release to Splunkbase.

**Comment by ccl0utier** [comment]
Mohammed, thanks a lot for such a quick turnaround and building this great visualization!  If you're interested in seeing how I'm using it, just ping me!
